__title__ = 'contactTree-api'
__package_name = 'contactTree-api'
__version__ = '0.1.0'
__description__ = ''
__author__ = 'Dionisis Pettas'
__email__ = ''
__github__  = 'https://github.com/deepettas/contact-tree'
__licence__ = 'MIT'